modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

issueTrackerURL="https://github.com/yourusername/ae2-pattern-highlighter/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2"
    mandatory=true
    versionRange="${ae2_version_range}"
    ordering="AFTER"
    side="BOTH"
